#!/usr/bin/env ruby

require_relative "lib/bmf.rb"
require 'thread'

def sync
  @new_messages = MessageStore.instance.update
  AddressStore.instance.update

  rescue Errno::ECONNREFUSED => ex
    puts "Couldn't connect to PyBitmessage server.  Is it running with the API enabled? " 
  rescue JSON::ParserError => ex
    puts "Couldn't sync.  It seems like PyBitmessage is running but refused access.  Do you have the correct info in config/settings.yml? "
end

puts "Doing initial sync before starting..."
sync

Thread.new do

  while(1) do
    sync_interval = Settings.instance.sync_interval.to_i
    sync_interval = 60 if sync_interval == 0
    puts "Background sync sleeping for #{sync_interval} seconds..."
    sleep(sync_interval)
    begin
      puts "Initiating background sync..."
      sync
    rescue Exception => ex
      puts "Background sync faild with #{ex.message}"
      puts ex.backtrace.join("\n")
    end

    puts "Finished background sync"
  end
  
end

BMF.run!
